# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Ingredient.create(name: "Lemon Juice")
Ingredient.create(name: "Ice")
Ingredient.create(name: "Mint Leaves")
Ingredient.create(name: "Espresso Shot")
Ingredient.create(name: "Brown Sugar")
Ingredient.create(name: "Juniper")
Ingredient.create(name: "Tonic water")
Ingredient.create(name: "Lime Juice")
Ingredient.create(name: "Black Pepper")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "London Dry Gin")
Ingredient.create(name: "Bourbon Whisky")
Ingredient.create(name: "Coca Cola")
Ingredient.create(name: "Triple Sec")
Ingredient.create(name: "Orange Peel")
Ingredient.create(name: "Dry Vermouth")
Ingredient.create(name: "Sugar Syrup")
Ingredient.create(name: "Light White Rum")
Ingredient.create(name: "Angostura Aromatic Bitters")
Ingredient.create(name: "Orange Juice")
Ingredient.create(name: "Cognac")
Ingredient.create(name: "Pineapple Juice")
Ingredient.create(name: "Sweet Vermouth")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Soda")
Ingredient.create(name: "Brut Champagne")
Ingredient.create(name: "Coffee Liquer")
